print('Programa que mostra operadores lógicos e relacionais')
a = int(2)
b = int(3)
c = int(5)
print('a = {}'.format(a))
print('b = {}'.format(b))
print('c = {}'.format(c))
print('a >  b = {}'.format(a > b))
print('a < b = {}'.format(a < b))
print('a >= 2 = {}'.format(a >= 2))
print('a <= c = {}'.format(a <= c))
print('c = a + b = {}'.format(c == a+c))
print('a diferente b = {}'.format(a != b))
