print('Programa que calcula dois valores inteiros e calcula sua média REAL')
a = int(input('Digite o primeiro valor: '))
b = int(input('Digite o segundo valor: '))
m = float((a + b) / 2)
print('A média é: {}'.format(m))
