print('Programa que verifica se o triângulo é equilátero ou escaleno')
l1 = float(input('Digite um valor para o primeiro lado: '))
l2 = float(input('Digite um valor para o segundo lado: '))
l3 = float(input('Digite um valor para o terceiro lado: '))
tri = bool((l1 < l2+l3) and(l2 < l1+l3) and (l3 < l1+l2))
eq = bool((l1 == l2) and (l2 == l3))
es = bool((l1 != l2) and (l2 != l3) and (l1 != l3))
print('Pode formar um triângulo: {}'.format(tri))
print('O triângulo é equilátero: {}'.format(eq))
print('O triângulo é escaleno: {}'.format(es))
