print('Operadores lógicos de E, OU, NÃO')
verdadeiro = bool(True)
falso = bool(False)
print('\nOperador E = and')
print(verdadeiro and verdadeiro)
print(verdadeiro and falso)
print(falso and verdadeiro)
print(falso and falso)
print('\nOperador OU = or')
print(verdadeiro or verdadeiro)
print(verdadeiro or falso)
print(falso or verdadeiro)
print(falso or falso)
print('\nOperador NÂO = not')
print(not verdadeiro)
print(not falso)
